// Code generated by mockery v2.20.0. DO NOT EDIT.

package coordinator

import mock "github.com/stretchr/testify/mock"

// MockErrorReporter is an autogenerated mock type for the ErrorReporter type
type MockErrorReporter struct {
	mock.Mock
}

type MockErrorReporter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockErrorReporter) EXPECT() *MockErrorReporter_Expecter {
	return &MockErrorReporter_Expecter{mock: &_m.Mock}
}

type mockConstructorTestingTNewMockErrorReporter interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockErrorReporter creates a new instance of MockErrorReporter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockErrorReporter(t mockConstructorTestingTNewMockErrorReporter) *MockErrorReporter {
	mock := &MockErrorReporter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
