// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Code generated by mockery v2.23.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	state "github.com/elastic/elastic-agent/internal/pkg/agent/application/upgrade/migration/state"
)

// MigrationStateReadWriter is an autogenerated mock type for the MigrationStateReadWriter type
type MigrationStateReadWriter struct {
	mock.Mock
}

type MigrationStateReadWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MigrationStateReadWriter) EXPECT() *MigrationStateReadWriter_Expecter {
	return &MigrationStateReadWriter_Expecter{mock: &_m.Mock}
}

// Read provides a mock function with given fields:
func (_m *MigrationStateReadWriter) Read() (*state.MigrationState, error) {
	ret := _m.Called()

	var r0 *state.MigrationState
	var r1 error
	if rf, ok := ret.Get(0).(func() (*state.MigrationState, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *state.MigrationState); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*state.MigrationState)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MigrationStateReadWriter_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MigrationStateReadWriter_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
func (_e *MigrationStateReadWriter_Expecter) Read() *MigrationStateReadWriter_Read_Call {
	return &MigrationStateReadWriter_Read_Call{Call: _e.mock.On("Read")}
}

func (_c *MigrationStateReadWriter_Read_Call) Run(run func()) *MigrationStateReadWriter_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MigrationStateReadWriter_Read_Call) Return(_a0 *state.MigrationState, _a1 error) *MigrationStateReadWriter_Read_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MigrationStateReadWriter_Read_Call) RunAndReturn(run func() (*state.MigrationState, error)) *MigrationStateReadWriter_Read_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function with given fields: _a0
func (_m *MigrationStateReadWriter) Write(_a0 *state.MigrationState) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*state.MigrationState) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MigrationStateReadWriter_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type MigrationStateReadWriter_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - _a0 *state.MigrationState
func (_e *MigrationStateReadWriter_Expecter) Write(_a0 interface{}) *MigrationStateReadWriter_Write_Call {
	return &MigrationStateReadWriter_Write_Call{Call: _e.mock.On("Write", _a0)}
}

func (_c *MigrationStateReadWriter_Write_Call) Run(run func(_a0 *state.MigrationState)) *MigrationStateReadWriter_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*state.MigrationState))
	})
	return _c
}

func (_c *MigrationStateReadWriter_Write_Call) Return(_a0 error) *MigrationStateReadWriter_Write_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MigrationStateReadWriter_Write_Call) RunAndReturn(run func(*state.MigrationState) error) *MigrationStateReadWriter_Write_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMigrationStateReadWriter interface {
	mock.TestingT
	Cleanup(func())
}

// NewMigrationStateReadWriter creates a new instance of MigrationStateReadWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMigrationStateReadWriter(t mockConstructorTestingTNewMigrationStateReadWriter) *MigrationStateReadWriter {
	mock := &MigrationStateReadWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
