// Code generated by mockery v2.23.1. DO NOT EDIT.

// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

package mocks

import (
	upgrade "github.com/elastic/elastic-agent/internal/pkg/agent/application/upgrade"
	mock "github.com/stretchr/testify/mock"
)

// UpdateMarkerReadWriter is an autogenerated mock type for the UpdateMarkerReadWriter type
type UpdateMarkerReadWriter struct {
	mock.Mock
}

type UpdateMarkerReadWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *UpdateMarkerReadWriter) EXPECT() *UpdateMarkerReadWriter_Expecter {
	return &UpdateMarkerReadWriter_Expecter{mock: &_m.Mock}
}

// Read provides a mock function with given fields:
func (_m *UpdateMarkerReadWriter) Read() (*upgrade.UpdateMarker, error) {
	ret := _m.Called()

	var r0 *upgrade.UpdateMarker
	var r1 error
	if rf, ok := ret.Get(0).(func() (*upgrade.UpdateMarker, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *upgrade.UpdateMarker); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*upgrade.UpdateMarker)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateMarkerReadWriter_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type UpdateMarkerReadWriter_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
func (_e *UpdateMarkerReadWriter_Expecter) Read() *UpdateMarkerReadWriter_Read_Call {
	return &UpdateMarkerReadWriter_Read_Call{Call: _e.mock.On("Read")}
}

func (_c *UpdateMarkerReadWriter_Read_Call) Run(run func()) *UpdateMarkerReadWriter_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UpdateMarkerReadWriter_Read_Call) Return(_a0 *upgrade.UpdateMarker, _a1 error) *UpdateMarkerReadWriter_Read_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UpdateMarkerReadWriter_Read_Call) RunAndReturn(run func() (*upgrade.UpdateMarker, error)) *UpdateMarkerReadWriter_Read_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function with given fields: _a0
func (_m *UpdateMarkerReadWriter) Write(_a0 *upgrade.UpdateMarker) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*upgrade.UpdateMarker) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateMarkerReadWriter_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type UpdateMarkerReadWriter_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - _a0 *upgrade.UpdateMarker
func (_e *UpdateMarkerReadWriter_Expecter) Write(_a0 interface{}) *UpdateMarkerReadWriter_Write_Call {
	return &UpdateMarkerReadWriter_Write_Call{Call: _e.mock.On("Write", _a0)}
}

func (_c *UpdateMarkerReadWriter_Write_Call) Run(run func(_a0 *upgrade.UpdateMarker)) *UpdateMarkerReadWriter_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*upgrade.UpdateMarker))
	})
	return _c
}

func (_c *UpdateMarkerReadWriter_Write_Call) Return(_a0 error) *UpdateMarkerReadWriter_Write_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UpdateMarkerReadWriter_Write_Call) RunAndReturn(run func(*upgrade.UpdateMarker) error) *UpdateMarkerReadWriter_Write_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewUpdateMarkerReadWriter interface {
	mock.TestingT
	Cleanup(func())
}

// NewUpdateMarkerReadWriter creates a new instance of UpdateMarkerReadWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUpdateMarkerReadWriter(t mockConstructorTestingTNewUpdateMarkerReadWriter) *UpdateMarkerReadWriter {
	mock := &UpdateMarkerReadWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
