// Code generated by mockery v2.23.1. DO NOT EDIT.

// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

package mocks

import (
	upgrade "github.com/elastic/elastic-agent/internal/pkg/agent/application/upgrade"
	mock "github.com/stretchr/testify/mock"
)

// UpgradeMarkerReadWriter is an autogenerated mock type for the UpgradeMarkerReadWriter type
type UpgradeMarkerReadWriter struct {
	mock.Mock
}

type UpgradeMarkerReadWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *UpgradeMarkerReadWriter) EXPECT() *UpgradeMarkerReadWriter_Expecter {
	return &UpgradeMarkerReadWriter_Expecter{mock: &_m.Mock}
}

// Read provides a mock function with given fields:
func (_m *UpgradeMarkerReadWriter) Read() (*upgrade.UpdateMarker, error) {
	ret := _m.Called()

	var r0 *upgrade.UpdateMarker
	var r1 error
	if rf, ok := ret.Get(0).(func() (*upgrade.UpdateMarker, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *upgrade.UpdateMarker); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*upgrade.UpdateMarker)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpgradeMarkerReadWriter_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type UpgradeMarkerReadWriter_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
func (_e *UpgradeMarkerReadWriter_Expecter) Read() *UpgradeMarkerReadWriter_Read_Call {
	return &UpgradeMarkerReadWriter_Read_Call{Call: _e.mock.On("Read")}
}

func (_c *UpgradeMarkerReadWriter_Read_Call) Run(run func()) *UpgradeMarkerReadWriter_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UpgradeMarkerReadWriter_Read_Call) Return(_a0 *upgrade.UpdateMarker, _a1 error) *UpgradeMarkerReadWriter_Read_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UpgradeMarkerReadWriter_Read_Call) RunAndReturn(run func() (*upgrade.UpdateMarker, error)) *UpgradeMarkerReadWriter_Read_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function with given fields: _a0
func (_m *UpgradeMarkerReadWriter) Write(_a0 *upgrade.UpdateMarker) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*upgrade.UpdateMarker) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpgradeMarkerReadWriter_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type UpgradeMarkerReadWriter_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - _a0 *upgrade.UpdateMarker
func (_e *UpgradeMarkerReadWriter_Expecter) Write(_a0 interface{}) *UpgradeMarkerReadWriter_Write_Call {
	return &UpgradeMarkerReadWriter_Write_Call{Call: _e.mock.On("Write", _a0)}
}

func (_c *UpgradeMarkerReadWriter_Write_Call) Run(run func(_a0 *upgrade.UpdateMarker)) *UpgradeMarkerReadWriter_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*upgrade.UpdateMarker))
	})
	return _c
}

func (_c *UpgradeMarkerReadWriter_Write_Call) Return(_a0 error) *UpgradeMarkerReadWriter_Write_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UpgradeMarkerReadWriter_Write_Call) RunAndReturn(run func(*upgrade.UpdateMarker) error) *UpgradeMarkerReadWriter_Write_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewUpgradeMarkerReadWriter interface {
	mock.TestingT
	Cleanup(func())
}

// NewUpgradeMarkerReadWriter creates a new instance of UpgradeMarkerReadWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUpgradeMarkerReadWriter(t mockConstructorTestingTNewUpgradeMarkerReadWriter) *UpgradeMarkerReadWriter {
	mock := &UpgradeMarkerReadWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
